sudo: false
language: python
python:
  - "3.7.3"
#addons:
  #postgresql: "9.4"
install:
  - pip install pip-tools wheel
  - pip install -r requirements.txt
before_script:
  - createuser -U postgres -d task2
  - createdb -U postgres -O task2 task2
script:
  - python manage.py test