stages:
  - test

test_job1:
  stage: test
  image: python:3.6
  services:
    - postgres:latest
  variables:
    DATABASE_URL: 'postgres://postgres:password@postgres:5432/vpagedb_new_270619'
  before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - apt install -y postgresql postgresql-contrib postgresql-client libpq-dev
    - pip install -r requirements.txt
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - python manage.py test
