sudo: true
language: python
python:
  - "3.7"
addons:
  postgresql: "9.4"
install:
  - sudo apt install python-pkg-resources
  - pip install wheel
  - pip install -r requirements.txt
before_script:
  - createuser -U postgres -d task2
  - createdb -U postgres -O task2 task2
script:
  - flake8 myapp
  - python manage.py test