# Generated by Django 2.1.3 on 2019-10-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='branch',
            new_name='company',
        ),
    ]
